apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
spec:
  ports:
    - name: "9191"
      protocol: TCP
      port: 9191
      targetPort: 8080
  selector:
    app: app