apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: host.minikube.internal:5432
            - name: DB_NAME  # Setting Database name
              value: customer
            - name: DB_USERNAME  # Setting Database username
              value: postgres
            - name: DB_PASSWORD # Setting Database password
              value: "123"
          image: tkoteshwar/sha256:4fa8bc6e5faa
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
      #restartPolicy: Always
