apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
    tier: database
  name: db
spec:
  ports:
    - name: "9292"
      port: 9292
      targetPort: 5432
  selector:
    app: db
    tier: database
    clusterIP: None

